services:
  - type: web
    name: day4-flask
    runtime: python
    buildCommand: bash build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.12"
      - key: DB_PATH
        value: /opt/render/project/src/board.db
