services:
  - type: web
    name: day4-flask
    runtime: python
    buildCommand: bash build.sh
    startCommand: gunicorn app:app
    disk:
      name: board-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.12"
      - key: DB_PATH
        value: /var/data/board.db
      - key: POSTS_SEED_PATH
        value: /opt/render/project/src/seed/local_posts_seed.json
